name: NASA project CI
on: 
   push:
        branches: [ Main ]
   pull_request:
          branches: [ Main ]
jobs:
   build:
    env:
      CI: true
    strategy:
      matrix:
         node-version: [20.x, 16.x]  
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Use Node.js version ${{ matrix.node-version}}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
      - run: npm install
      # - run: npm run build --prefix client  
      - run: npm start
      - run: npm test 
             